#!/usr/bin/env python

# parse input into grid of number
with open("input") as f:
    m = f.read()
alpha = "abcdefghijklmnopqrstuvwxyz"
grid = []
for y,l in enumerate(m.split()):
    line = []
    for x,letter in enumerate(l):
        if letter == "S":
            letter = "a"
            xs, ys = x, y
        elif letter == "E":
            letter = "z"
            xe, ye = x, y
        line.append(alpha.index(letter))
    grid.append(line)

# width and height
w = len(grid[0])
h = len(grid)


def bfs(start, end, part2=False):
    xs, ys = start
    xe, ye = end

    # create list of visited cells
    visited = []
    for _ in range(h):
        visited.append([0]*w)

    # S is visited
    visited[ys][xs] = 1
    neighbors = [(xs, ys)]

    steps = 0
    while True:
        steps += 1
        next_neighbors = []

        # use old neighbors
        for (x, y) in neighbors:
            height = grid[y][x]

            # to iterate over next potential neighbors
            for xi, yi in [(-1, 0), (1, 0), (0, 1), (0, -1)]:
                    xt = x+xi
                    yt = y+yi

                    if not (0<=xt<w and 0<=yt<h): # check if in grid
                        continue
                    if visited[yt][xt]: # check if visited
                        continue
                    if grid[yt][xt] > height + 1: # check if too high
                        continue
                    if grid[yt][xt] == 0 and part2:
                        return steps
                    if (xt, yt) == (xe, ye): # check if answer found
                        return steps
                    
                    # next neighbor found
                    visited[yt][xt] = 1
                    next_neighbors.append((xt, yt)) 

        neighbors = next_neighbors

out = bfs((xs, ys), (xe, ye))
print("part1:", out)

out = bfs((xe, ye), (xs, ys), part2=True)
print("part2:", out)
